apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira.fullname" . }}-config
  labels:
    {{- include "jira.labels" . | nindent 4 }}
data:
  jira-config.properties: |
    {{- range .Values.jira.additionalJiraConfigs }}
    {{ . }}
    {{- end }}
