apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
rules:
{{ if .Capabilities.APIVersions.Has "policy/v1beta1" -}}
- apiGroups: ['policy']
{{- else -}}
- apiGroups: ['extensions']
{{- end }}
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "jira.fullname" . }}