apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 0.14.0
appVersion: 8.13.9-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://www.atlassian.com/software/jira
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: Update Jira version to 8.13.9-jdk11
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/212