{{- if and .Values.confluence.clustering.enabled .Values.serviceAccount.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "confluence.clusterRoleName" . }}
  labels:
  {{- include "confluence.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
    verbs:
      - get
      - list
{{- end -}}