{{- if .Values.database.credentials.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.credentials.secretName }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
data:
  {{ .Values.database.credentials.usernameSecretKey }}: {{ .Values.database.credentials.usernameSecretValue }}
  {{ .Values.database.credentials.passwordSecretKey }}: {{ .Values.database.credentials.passwordSecretValue }}
type: Opaque
{{- end -}}
