apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 0.14.0
appVersion: 7.12.3-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Confluence
  - Confluence Server
  - Confluence Data Center
  - Confluence DC
  - Atlassian
home: https://www.atlassian.com/software/confluence
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/confluence.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update Confluence version to 7.12.3-jdk11
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/212